# Generated by Django 3.2.7 on 2021-09-27 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createportfolio',
            fields=[
                ('template_url', models.SlugField(primary_key=True, serialize=False)),
                ('landing_page', models.URLField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('about_image', models.URLField(blank=True)),
                ('about_info', models.CharField(max_length=1000)),
                ('p1_title', models.CharField(max_length=50)),
                ('p1_content', models.CharField(max_length=500)),
                ('p1_url', models.URLField()),
                ('p2_title', models.CharField(max_length=50)),
                ('p2_content', models.CharField(max_length=500)),
                ('p2_url', models.URLField()),
                ('p3_title', models.CharField(max_length=50)),
                ('p3_content', models.CharField(max_length=500)),
                ('p3_url', models.URLField()),
                ('instagram', models.URLField(blank=True)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('gmail', models.URLField()),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
