# Generated by Django 3.2.7 on 2021-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_createportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='createportfolio',
            name='brand_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createportfolio',
            name='heading',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
