# Generated by Django 3.2.7 on 2021-09-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210927_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createportfolio',
            name='template_url',
        ),
        migrations.AddField(
            model_name='createportfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
