# Generated by Django 3.2.7 on 2021-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210928_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='createportfolio',
            name='templates',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
