# Generated by Django 3.2.7 on 2021-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_createportfolio_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createportfolio',
            name='templates',
            field=models.CharField(choices=[('Template-1', 'Template-1'), ('Template-2', 'Template-2'), ('Template-3', 'Template-3')], default=1, max_length=122),
        ),
    ]
