# Generated by Django 3.2.7 on 2021-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210928_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createportfolio',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='createportfolio',
            old_name='subtitle',
            new_name='prof',
        ),
        migrations.RemoveField(
            model_name='createportfolio',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='createportfolio',
            name='landing_page',
        ),
        migrations.AlterField(
            model_name='createportfolio',
            name='templates',
            field=models.CharField(choices=[('Template-1', 'Template-1.html'), ('Template-2', 'Template-2.html'), ('Template-3', 'Template-3.html')], default=1, max_length=122),
        ),
    ]
