# Generated by Django 3.2.7 on 2021-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210929_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createportfolio',
            name='template_url',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
